export default {
  getCredentials: state => state.credentials,
  getCurrentPlayback: state => state.currentPlayback,
  getPlaylists: state => state.playlists.items,
  getDuration: state => state.currentPlayback.item.duration_ms,
  getProgress: state => state.currentPlayback.progress_ms,
  getDeviceId: state => state.currentPlayback.device.id,
  getCurrentUser: state => state.currentUser,
  getMarket: state => state.currentUser.country,
  getCountry: state => state.currentUser.country,
  getLocale: state => state.currentUser.country,
  getNotices: state => state.notices,
  getAppSettings: state => state.settings,
  getStageContent: state => state.stage,
};
